[refonte usager] Tableau de bord - Ajouter bouton filtres simples
demarche-numerique/demarche.numerique.gouv.fr pull request #8994
Opened 2023-05-02 14:06 UTC by lisa-durand

closes #8878 

<img width="1292" alt="Capture d’écran 2023-05-03 à 17 48 50" src="https://user-images.githubusercontent.com/6756627/235969565-789307e8-4c4b-4b30-9cef-0e48c23a9b89.png">
<img width="1300" alt="Capture d’écran 2023-05-03 à 17 49 19" src="https://user-images.githubusercontent.com/6756627/235969558-63ac0774-6874-443c-8798-80f53e8d9f03.png">
<img width="1278" alt="Capture d’écran 2023-05-03 à 17 49 32" src="https://user-images.githubusercontent.com/6756627/235969570-9ad86334-dcdf-469c-9682-f7833bf97c27.png">

2023-05-04 07:03 UTC, mfo commented on app/controllers/users/dossiers_controller.rb
> +    def filter_procedures(filter, dossiers)
que penses-tu de deplacer cette methode dans `DossiersFilter` ? et d'y passer de manière inconditionnelle depuis le controller ? en gros qqch comme : 
```
@filter = DossiersFilter.new(current_user, params)
@dossier = @filter.apply(dossiers)
```

et 
```
def filter_procedures(filter, dossiers)
  return dossiers if !filter_params?
  ...
```

2023-05-04 07:18 UTC, mfo commented on app/components/dossiers/user_filter_component/user_filter_component.html.haml
> +              %fieldset#checkboxes.fr-fieldset{ "aria-labelledby" => "checkboxes-legend checkboxes-messages" }
```suggestion
              %fieldset#checkboxes.fr-fieldset{ "aria-labelledby" => "checkboxes-legend" }
```

2023-05-04 07:20 UTC, mfo commented on app/components/dossiers/user_filter_component/user_filter_component.html.haml
> +    %nav.fr-translate.fr-nav
❤️  j'avais un doute sur l'usage du `.fr-translate` pour ce dropdown (genre nav au clavier etc...). 
🤩 ça fonctionne parfaitement ! 🤩  

maintenant je me demande si il faudra en étendre l'usage la ou on utilise notre dropdown en mode region (voir le componentiser pour un usage plus facile)

2023-05-04 07:21 UTC, mfo commented on app/models/dossiers_filter.rb
> +  ITEMS_PER_PAGE = 25
```suggestion
```

2023-05-04 07:22 UTC, mfo commented on app/views/users/dossiers/index.html.haml
> +      = render user_filter_component
possible que tu essaies ça 

```suggestion
    = Dossiers::UserFilterComponent.new(statut: @statut, filter: @filter)
```
je crois que le `render?` du composant suffit

2023-05-04 07:23 UTC, mfo requested changes
déjà canon la PR ! juste un micro fix d'a11y. sinon c'est parfait

2023-05-04 10:34 UTC, lisa-durand commented on app/components/dossiers/user_filter_component/user_filter_component.html.haml
> +    %nav.fr-translate.fr-nav
Top si ça fonctionne bien ! Pour étendre l'usage, ça me parait prématuré car j'ai un peu détourné le fonctionnement du sélecteur de langue en attendant le dropdown DSFR officiel. Il ne devrait pas tarder, selon les dernieres discussions qu'a eu Olivier avec l'equipe DSFR.

2023-05-04 11:21 UTC, tchak commented on app/components/dossiers/user_filter_component/user_filter_component.html.haml
> +    %nav.fr-translate.fr-nav
Je suppose que ça marche ici car ce n'est pas un vrai menu mais un popover. `fr-translate` n'implémentera pas la navigation avec les flèches comme c'est fait dans notre implémentation. Notre implémentation à nous dispose de deux modes `menu` et `popover`.
-  Un `popover` est un panel qui s'ouvre à côté d'un bouton avec des éléments d'interface à l'intérieur. Idéalement, on devrait capturer le focus comme dans une modale. On navigue à l'intérieur avec la touche tab.
-  Un `menu` ouvre une liste d'actions. On navigue à l'intérieur avec les flèches.

2023-05-05 07:18 UTC, mfo commented on app/components/dossiers/user_filter_component/user_filter_component.html.haml
> +    %nav.fr-translate.fr-nav
merci pr ces clarifications Paul. le mode `popover` etait ce que j'entendais par `region`. Le cas du `.fr-translate` gere bien la sorti du focus (mieux que nous je crois). Mais oui attendons la sortie officielle (pour le menu, notre composant fonctionne mieux)

2023-05-05 07:19 UTC, mfo approved these changes

2023-05-09 08:15 UTC, merged